-- 019_scout_evaluations.sql
-- Per-scout manual evaluations — each scout can rate a player independently
-- Replaces the single observer_eval field with multi-scout ratings

CREATE TABLE IF NOT EXISTS scout_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  -- One evaluation per scout per player
  UNIQUE (player_id, user_id)
);

-- RLS policies
ALTER TABLE scout_evaluations ENABLE ROW LEVEL SECURITY;

-- Everyone can read all evaluations
CREATE POLICY "scout_evaluations_select" ON scout_evaluations
  FOR SELECT USING (true);

-- Authenticated users can insert their own evaluations
CREATE POLICY "scout_evaluations_insert" ON scout_evaluations
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can update their own evaluations
CREATE POLICY "scout_evaluations_update" ON scout_evaluations
  FOR UPDATE USING (auth.uid() = user_id);

-- Users can delete their own evaluations; admins can delete any
CREATE POLICY "scout_evaluations_delete" ON scout_evaluations
  FOR DELETE USING (
    auth.uid() = user_id
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Index for fast lookups by player
CREATE INDEX IF NOT EXISTS idx_scout_evaluations_player ON scout_evaluations(player_id);
