// src/lib/__tests__/factories.ts
// Test factory functions for domain objects — prevents cross-test contamination
// Use makePlayer(), makePlayerRow(), etc. with optional overrides
// RELEVANT FILES: src/lib/types/index.ts, src/lib/supabase/mappers.ts

import type {
  CalendarEventRow,
  Player,
  PlayerRow,
  ScoutingReportRow,
} from '@/lib/types';

/* ───────────── Player (domain) ───────────── */

export function makePlayer(overrides?: Partial<Player>): Player {
  return {
    id: 1,
    ageGroupId: 10,
    name: 'João Silva',
    dob: '2012-03-15',
    club: 'Boavista FC',
    positionOriginal: 'Defesa Central',
    positionNormalized: 'DC',
    secondaryPosition: null,
    tertiaryPosition: null,
    foot: 'Dir',
    shirtNumber: '4',
    contact: '',
    departmentOpinion: ['Acompanhar'],
    observer: 'Carlos Lopes',
    observerEval: '4 - Muito Bom',
    observerDecision: 'Acompanhar',
    referredBy: '',
    referredByUserId: null,
    notes: '',
    reportLabels: [],
    reportLinks: [],
    fpfLink: '',
    fpfPlayerId: '',
    zerozeroLink: '',
    zerozeroPlayerId: '',
    fpfCurrentClub: null,
    fpfLastChecked: null,
    zzCurrentClub: null,
    zzCurrentTeam: null,
    zzGamesSeason: null,
    zzGoalsSeason: null,
    zzHeight: null,
    zzWeight: null,
    height: null,
    weight: null,
    birthCountry: null,
    nationality: null,
    photoUrl: null,
    zzPhotoUrl: null,
    clubLogoUrl: null,
    zzTeamHistory: null,
    zzLastChecked: null,
    recruitmentStatus: null,
    trainingDate: null,
    meetingDate: null,
    signingDate: null,
    recruitmentNotes: '',
    isRealSquad: false,
    isShadowSquad: false,
    realSquadPosition: null,
    shadowPosition: null,
    shadowOrder: 0,
    realOrder: 0,
    pipelineOrder: 0,
    pendingApproval: false,
    adminReviewed: true,
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    reportAvgRating: null,
    reportRatingCount: 0,
    observationNotePreviews: [],
    ...overrides,
  };
}

/* ───────────── PlayerRow (DB snake_case) ───────────── */

export function makePlayerRow(overrides?: Partial<PlayerRow>): PlayerRow {
  return {
    id: 1,
    age_group_id: 10,
    name: 'João Silva',
    dob: '2012-03-15',
    club: 'Boavista FC',
    position_original: 'Defesa Central',
    position_normalized: 'DC',
    secondary_position: null,
    tertiary_position: null,
    foot: 'Dir',
    shirt_number: '4',
    contact: '',
    department_opinion: ['Acompanhar'],
    observer: 'Carlos Lopes',
    observer_eval: '4 - Muito Bom',
    observer_decision: 'Acompanhar',
    referred_by: '',
    referred_by_user_id: null,
    notes: '',
    report_label_1: null,
    report_label_2: null,
    report_label_3: null,
    report_label_4: null,
    report_label_5: null,
    report_label_6: null,
    report_link_1: null,
    report_link_2: null,
    report_link_3: null,
    report_link_4: null,
    report_link_5: null,
    report_link_6: null,
    fpf_link: null,
    fpf_player_id: null,
    zerozero_link: null,
    zerozero_player_id: null,
    fpf_current_club: null,
    fpf_last_checked: null,
    zz_current_club: null,
    zz_current_team: null,
    zz_games_season: null,
    zz_goals_season: null,
    zz_height: null,
    zz_weight: null,
    height: null,
    weight: null,
    birth_country: null,
    nationality: null,
    photo_url: null,
    zz_photo_url: null,
    club_logo_url: null,
    zz_team_history: null,
    zz_last_checked: null,
    recruitment_status: '',
    training_date: null,
    meeting_date: null,
    signing_date: null,
    recruitment_notes: null,
    is_real_squad: false,
    is_shadow_squad: false,
    real_squad_position: null,
    shadow_position: null,
    shadow_order: 0,
    real_order: 0,
    pipeline_order: 0,
    pending_approval: false,
    admin_reviewed: true,
    created_at: '2025-01-15T10:00:00Z',
    updated_at: '2025-01-15T10:00:00Z',
    created_by: null,
    ...overrides,
  };
}

/* ───────────── ScoutingReportRow (DB snake_case) ───────────── */

export function makeScoutingReportRow(overrides?: Partial<ScoutingReportRow>): ScoutingReportRow {
  return {
    id: 1,
    player_id: 1,
    gdrive_file_id: 'abc123',
    gdrive_link: 'https://drive.google.com/file/abc123',
    report_number: 1,
    pdf_filename: 'relatorio_joao_silva.pdf',
    competition: 'Campeonato Distrital Sub-14',
    age_group: 'Sub-14',
    match: 'Boavista vs Leixões',
    match_date: '2025-01-10',
    match_result: '2-1',
    player_name_report: 'João Silva',
    shirt_number_report: '4',
    birth_year_report: '2012',
    foot_report: 'Direito',
    team_report: 'Boavista FC',
    position_report: 'Defesa Central',
    physical_profile: 'Forte, bom jogo aéreo',
    strengths: 'Posicionamento, cabeceamento',
    weaknesses: 'Velocidade em espaço aberto',
    rating: 4,
    decision: 'Acompanhar',
    analysis: 'Jogador com potencial para o plantel.',
    contact_info: '',
    scout_name: 'Carlos Lopes',
    raw_text: null,
    extraction_status: 'success',
    extraction_error: null,
    extracted_at: '2025-01-12T09:00:00Z',
    created_at: '2025-01-12T09:00:00Z',
    ...overrides,
  };
}

/* ───────────── CalendarEventRow (DB snake_case) ───────────── */

export function makeCalendarEventRow(overrides?: Partial<CalendarEventRow>): CalendarEventRow {
  return {
    id: 1,
    age_group_id: 10,
    player_id: 1,
    event_type: 'treino',
    title: 'Treino de avaliação',
    event_date: '2025-02-15',
    event_time: '10:00',
    location: 'Complexo Desportivo do Bessa',
    notes: '',
    assignee_user_id: null,
    assignee_name: null,
    created_by: 'user-abc',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
    players: {
      name: 'João Silva',
      photo_url: null,
      zz_photo_url: null,
      club: 'Boavista FC',
      position_normalized: 'DC',
      dob: '2012-03-15',
      foot: 'Dir',
    },
    ...overrides,
  };
}
